NAME = libft.a

CC = gcc
CFLAGS = -Wall -Wextra -Werror

SRC =		ft_atoi.c		ft_bzero.c		ft_calloc.c		\
		ft_isalnum.c		ft_isalpha.c		ft_isascii.c		\
		ft_isdigit.c		ft_isprint.c		ft_itoa.c		\
		ft_memchr.c		ft_memcmp.c		ft_memcpy.c		\
		ft_memmove.c		ft_memset.c		ft_putchar_fd.c		\
		ft_putendl_fd.c		ft_putnbr_fd.c		ft_putstr_fd.c		\
		ft_split.c		ft_strchr.c		ft_strdup.c		\
		ft_striteri.c		ft_strjoin.c		ft_strlcat.c		\
		ft_strlcpy.c		ft_strlen.c		ft_strmapi.c		\
		ft_strncmp.c		ft_strnstr.c		ft_strrchr.c		\
		ft_strtrim.c		ft_substr.c		ft_tolower.c		\
		ft_toupper.c

SRC_BONUS =	ft_lstadd_back.c	ft_lstadd_front.c	ft_lstclear.c		\
		ft_lstdelone.c		ft_lstiter.c		ft_lstlast.c		\
		ft_lstmap.c		ft_lstnew.c		ft_lstsize.c

OBJ = $(SRC:.c=.o)
OBJ_BONUS = $(SRC_BONUS:.c=.o)

all : $(NAME)

$(NAME) :
	$(CC) -I $(CFLAGS) -c $(CFLAGS) $(SRC)
	ar -rcs $(NAME) $(OBJ)

bonus : $(OBJ) $(OBJ_BONUS)
	ar -rcs $(NAME) $(OBJ) $(OBJ_BONUS)

clean :
	rm -f $(OBJ) $(OBJ_BONUS)

fclean : clean
	rm -f $(NAME)

dev:
	make fclean;cd ../libft-unit-test; make f;cd ../libft; make fclean

re : fclean all

reb: fclean all bonus

rf : re
	rm -f $(OBJ) $(OBJ_BONUS)
	rm -f $(NAME)

s:	
	ls -lh $(NAME)

.PHONY: all bonus clean fclean re rf s dev
